{
 "title": "Consul Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Consul Cluster Members",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "consul_serf_lan_members" }
   ]
  },
  {
   "title": "Number of Consul Catalog Services",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "consul_catalog_services" }
   ]
  },
  {
   "title": "Node Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "consul_health_node_status{status=\"passing\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Raspberry Pi",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "consul_health_node_status{check=\"serfHealth\",instance=\"127.0.0.1:9107\",job=\"Consul Exporter\",node=\"raspberrypi\",status=\"passing\"}"
    }
   ]
  },
  {
   "title": "Consul Server",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "first",
   "targets": [
    {
     "expr": "consul_health_node_status{check=\"serfHealth\",instance=\"127.0.0.1:9107\",job=\"Consul Exporter\",node=\"Takayukis-MacBook-Pro.local\",status=\"passing\"}"
    }
   ]
  },
  {
   "title": "runtime_alloc_bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consul_raspberrypi_runtime_alloc_bytes"
    },
    {
     "expr": "consul_Takayukis_MacBook_Pro_local_runtime_alloc_bytes"
    }
   ]
  },
  {
   "title": "Runtime Sys Bytes",
   "type": "graph",
   "description": "This measures the number of bytes allocated by the Consul process.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consul_raspberrypi_runtime_sys_bytes"
    },
    {
     "expr": "consul_Takayukis_MacBook_Pro_local_runtime_sys_bytes"
    }
   ]
  },
  {
   "title": "runtime_heap_object",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consul_raspberrypi_runtime_heap_objects"
    },
    {
     "expr": "consul_Takayukis_MacBook_Pro_local_runtime_heap_objects"
    }
   ]
  },
  {
   "title": "num_goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consul_Takayukis_MacBook_Pro_local_runtime_num_goroutines"
    },
    {
     "expr": "consul_raspberrypi_runtime_num_goroutines"
    }
   ]
  },
  {
   "title": "Service Health History",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "consul_health_service_status{status=\"passing\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}